//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GithubVSAutomationIDs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutomationIDs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationIDs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GithubVSAutomationIDs.AutomationIDs", typeof(AutomationIDs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8FE5A4A9-2E3C-48D4-8351-8D4D959BD6F4.
        /// </summary>
        public static string Button_PullRequestCreationCancel {
            get {
                return ResourceManager.GetString("Button_PullRequestCreationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24E9EB8A-2441-441D-87CA-20CC7FBEF11F.
        /// </summary>
        public static string Button_PullRequestCreationCreate {
            get {
                return ResourceManager.GetString("Button_PullRequestCreationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70F8CBA0-EE79-4F75-81AA-39A5E4322FE5.
        /// </summary>
        public static string DropDown_PullRequestListFilterAssignees {
            get {
                return ResourceManager.GetString("DropDown_PullRequestListFilterAssignees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4F5B2AC6-D1F6-46B7-950D-D63619D9CA83.
        /// </summary>
        public static string DropDown_PullRequestTargetBranch {
            get {
                return ResourceManager.GetString("DropDown_PullRequestTargetBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5655ABA-9EEF-49EC-B74C-8DDB8E130AD5.
        /// </summary>
        public static string Label_PullRequestCreationSourceBranch {
            get {
                return ResourceManager.GetString("Label_PullRequestCreationSourceBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38E80A12-5E56-4E1B-9A0C-C71E503DAA76.
        /// </summary>
        public static string Modal_Gist {
            get {
                return ResourceManager.GetString("Modal_Gist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6E2404F-5526-42E1-AF59-58C1C78B9C1A.
        /// </summary>
        public static string Modal_LogIn {
            get {
                return ResourceManager.GetString("Modal_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9ABC39DE-13EA-4705-B461-35B9AE6F8E82.
        /// </summary>
        public static string Modal_RepositoryClone {
            get {
                return ResourceManager.GetString("Modal_RepositoryClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9768F66E-4C25-42E5-B4B8-15B7CF5BA254.
        /// </summary>
        public static string Modal_RepositoryCreate {
            get {
                return ResourceManager.GetString("Modal_RepositoryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1B63773B-3864-4CBD-8DA2-85D0B2CBB127.
        /// </summary>
        public static string Modal_TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("Modal_TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1832073F-538B-414A-8849-82192E4B5BC4.
        /// </summary>
        public static string Pane_GitHub {
            get {
                return ResourceManager.GetString("Pane_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D90E8907-A0B7-44B5-9D8F-FCDC2D891B7E.
        /// </summary>
        public static string Pane_PullRequestCreation {
            get {
                return ResourceManager.GetString("Pane_PullRequestCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70901982-B7DF-467C-91F2-672A92A8C3E1.
        /// </summary>
        public static string Pane_PullRequestCreationDetail {
            get {
                return ResourceManager.GetString("Pane_PullRequestCreationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D031AB2C-E81A-4926-97ED-2F19DD3BABB7.
        /// </summary>
        public static string Pane_PullRequestList {
            get {
                return ResourceManager.GetString("Pane_PullRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D1B99F04-3017-4A40-9669-79E1215C9B6D.
        /// </summary>
        public static string Panel_InfoPanel {
            get {
                return ResourceManager.GetString("Panel_InfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8868F4FE-D2F6-4C6D-AC43-355EC72AC316.
        /// </summary>
        public static string TextBox_PullRequestCreationDescription {
            get {
                return ResourceManager.GetString("TextBox_PullRequestCreationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64728EB8-5D48-403D-A34E-A4D3AE450840.
        /// </summary>
        public static string TextBox_PullRequestCreationTitle {
            get {
                return ResourceManager.GetString("TextBox_PullRequestCreationTitle", resourceCulture);
            }
        }
    }
}
