//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GithubVSAutomationIDs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutomationIDs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationIDs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GithubVSAutomationIDs.AutomationIDs", typeof(AutomationIDs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistModal.
        /// </summary>
        public static string GistModal {
            get {
                return ResourceManager.GetString("GistModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubInfoPanel.
        /// </summary>
        public static string GitHubInfoPanel {
            get {
                return ResourceManager.GetString("GitHubInfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubInfoPanelCancelButton.
        /// </summary>
        public static string GitHubInfoPanelCancelButton {
            get {
                return ResourceManager.GetString("GitHubInfoPanelCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubInfoPanelMessageDocument.
        /// </summary>
        public static string GitHubInfoPanelMessageDocument {
            get {
                return ResourceManager.GetString("GitHubInfoPanelMessageDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubLoggedOutCreateAnAccountHyperlink.
        /// </summary>
        public static string GitHubLoggedOutCreateAnAccountHyperlink {
            get {
                return ResourceManager.GetString("GitHubLoggedOutCreateAnAccountHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubLoggedOutSignInHyperlink.
        /// </summary>
        public static string GitHubLoggedOutSignInHyperlink {
            get {
                return ResourceManager.GetString("GitHubLoggedOutSignInHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubTabItem.
        /// </summary>
        public static string GitHubTabItem {
            get {
                return ResourceManager.GetString("GitHubTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBar.
        /// </summary>
        public static string GitHubToolBar {
            get {
                return ResourceManager.GetString("GitHubToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarBackImage.
        /// </summary>
        public static string GitHubToolBarBackImage {
            get {
                return ResourceManager.GetString("GitHubToolBarBackImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarForwardImage.
        /// </summary>
        public static string GitHubToolBarForwardImage {
            get {
                return ResourceManager.GetString("GitHubToolBarForwardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarPullRequestImage.
        /// </summary>
        public static string GitHubToolBarPullRequestImage {
            get {
                return ResourceManager.GetString("GitHubToolBarPullRequestImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarRefreshImage.
        /// </summary>
        public static string GitHubToolBarRefreshImage {
            get {
                return ResourceManager.GetString("GitHubToolBarRefreshImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggedOutViewCustom.
        /// </summary>
        public static string LoggedOutViewCustom {
            get {
                return ResourceManager.GetString("LoggedOutViewCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerfulCollaborationTextBlock.
        /// </summary>
        public static string PowerfulCollaborationTextBlock {
            get {
                return ResourceManager.GetString("PowerfulCollaborationTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationCancelButton.
        /// </summary>
        public static string PullRequestCreationCancelButton {
            get {
                return ResourceManager.GetString("PullRequestCreationCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationCreateButton.
        /// </summary>
        public static string PullRequestCreationCreateButton {
            get {
                return ResourceManager.GetString("PullRequestCreationCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationDescriptionTextBox.
        /// </summary>
        public static string PullRequestCreationDescriptionTextBox {
            get {
                return ResourceManager.GetString("PullRequestCreationDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationDetailPane.
        /// </summary>
        public static string PullRequestCreationDetailPane {
            get {
                return ResourceManager.GetString("PullRequestCreationDetailPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationPane.
        /// </summary>
        public static string PullRequestCreationPane {
            get {
                return ResourceManager.GetString("PullRequestCreationPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationSourceBranchLabel.
        /// </summary>
        public static string PullRequestCreationSourceBranchLabel {
            get {
                return ResourceManager.GetString("PullRequestCreationSourceBranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationTitleTextBox.
        /// </summary>
        public static string PullRequestCreationTitleTextBox {
            get {
                return ResourceManager.GetString("PullRequestCreationTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListFilterAssigneesDropDown.
        /// </summary>
        public static string PullRequestListFilterAssigneesDropDown {
            get {
                return ResourceManager.GetString("PullRequestListFilterAssigneesDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListPane.
        /// </summary>
        public static string PullRequestListPane {
            get {
                return ResourceManager.GetString("PullRequestListPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestTargetBranchDropDown.
        /// </summary>
        public static string PullRequestTargetBranchDropDown {
            get {
                return ResourceManager.GetString("PullRequestTargetBranchDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryCloneModal.
        /// </summary>
        public static string RepositoryCloneModal {
            get {
                return ResourceManager.GetString("RepositoryCloneModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryCreateModal.
        /// </summary>
        public static string RepositoryCreateModal {
            get {
                return ResourceManager.GetString("RepositoryCreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInModal.
        /// </summary>
        public static string SignInModal {
            get {
                return ResourceManager.GetString("SignInModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInToGitHubTextBlock.
        /// </summary>
        public static string SignInToGitHubTextBlock {
            get {
                return ResourceManager.GetString("SignInToGitHubTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationModal.
        /// </summary>
        public static string TwoFactorAuthenticationModal {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationModal", resourceCulture);
            }
        }
    }
}
